name: Futuramaapi

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        pip install -r requirements.txt
    - name: Ruff
      run: |
        ruff --output-format=github .
    - name: Pytest
      run: |
        python -m pytest -p tests.plugins.env_vars
